config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'
  get '/user_friends',           to: 'friends#show',  as: :friends
  get '/user_likes',             to: 'likes#index',   as: :likes
  get '/user_birthday',          to: 'birthday#show', as: :birthday
  get '/auth/facebook/callback', to: 'sessions#create'
  delete '/logout',              to: 'sessions#destroy'
  get '/auth/facebook',          as: :login
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  def self.from_omniauth(auth)
    user = User.find_or_create_by(uid:auth["uid"])
    user.uid              = auth['uid']
    user.provider         = auth['provider']
    user.email            = auth['info']['email']
    user.name             = auth['info']['name']
    user.image            = auth['info']['image']
    user.oauth_token      = auth['credentials']['token']
    user.oauth_expires_at = auth['credentials']['expires_at']
    user.save
    user
  end
end

app/models/user_likes.rb
class UserLikes
  attr_reader :name
  def initialize(attrs = {})
    @name = attrs[:name]
  end

  def self.for_user(current_user)
    FacebookService.new(current_user).user_likes.map do |raw_like|
      UserLikes.new(raw_like)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/birthday_controller.rb
class BirthdayController < ApplicationController
  def show
    @presenter = UserPresenter.new(current_user)
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def show
    @presenter = UserPresenter.new(current_user)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @presenter = UserPresenter.new(current_user)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def index
    @presenter = UserPresenter.new(current_user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    if user
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/birthday/show.html.erb
<div class="position">
  <h1><%= @presenter.user_birthday %></h1>  
</div>

app/views/friends/show.html.erb
<div class="position">
  <span><%= @presenter.user_friends_count %></span>
</div>

app/views/home/index.html.erb
<% if current_user %>
<h1>Signed in as, <%= current_user.name %>!</h1>
  <div class="position">
      <%= image_tag @presenter.user_image %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Facebook API</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>

<div class="background">
  <body>
    <ul class="nav nav-pills">
      <% if current_user %>
      <li role="presentation" class="active"> <%= link_to "Profile Photo!", root_path %> </li>
      <li role="presentation" class="active"> <%= link_to "Likes!", likes_path %> </li>
      <li role="presentation" class="active"> <%= link_to "Birthday!", birthday_path %> </li>
      <li role="presentation" class="active"> <%= link_to "Friends!", friends_path %> </li>
      <li role="presentation" class="active"><%= link_to "Sign Out", logout_path, method: :delete %></a></li>
      <% else %>
      <li role="presentation" class="active"><%= link_to "Sign in with Facebook", login_path %></li>
      <% end %>
    </ul>
    <%= yield %>
  </body>
</div>
</html>

app/views/likes/index.html.erb
<div class="center">
  <% @presenter.user_likes.each do |like| %>
  <div class="white">
    <%= like.name %><br>
  </div>
  <% end %>
</div>